### ISSUE TITLE
Can't login

### ISSUE THREAD

**Issue by muznyo** [krafairus/com.krafairus.BardGoogle#1]
When trying to login, it opens google gemini in browser instead.

**Comment by krafairus** [comment]
@muznyo Hello, good morning (afternoon or night), I realized this yesterday when I entered the website, the problem comes from the bard google website, which is now called gemini google, the login button started to work differently, now the website opens another tab. For that, I am looking at how to solve it, although this project is based on another, the other one has no problems because it uses chatgpt, and Google's is the one that works differently on the web. I'll see what I can do, thanks for letting me know.

**Comment by krafairus** [comment]
@muznyo I already updated the package and it solved the problem, if you have another problem using this plasmoid, please let me know.

**Comment by muznyo** [comment]
Now i can login, only problem is light scrollbars when using dark mode, but its probably google's issue? 
![image](https://github.com/krafairus/com.krafairus.GeminiGoogle/assets/24987471/391a6638-a7df-499a-badb-50c06acaf0f4)

**Comment by krafairus** [comment]
@muznyo You are correct, it is a web problem.
